"""
Справочник товаров Mini App.

Каталог в боте через инлайн-кнопки удалён — выбор и корзина в TMA,
а витрина загружает этот список через /api/catalog.
"""
MINI_APP_CATEGORIES = (
    {"id": "all", "title": "Все товары"},
    {"id": "ready_meals", "title": "Готовая еда"},
    {"id": "sausage", "title": "Колбасы"},
    {"id": "horsemeat", "title": "Конина"},
    {"id": "steak", "title": "Стейки"},
    {"id": "fat", "title": "Жир"},
)

MINI_APP_PRODUCT_CATALOG = (
    {
        "id": "buckwheat_chicken",
        "title": "Гречка с курицей",
        "categoryId": "ready_meals",
        "emoji": "🍲",
        "price": 350,
        "image": "images/products/buckwheat_chicken.jpg",
        "unit": "за порцию",
        "description": "Сублимированное готовое блюдо: гречка с курицей. Удобно для дома, дороги, спорта и поездок.",
    },
    {
        "id": "rice_chicken",
        "title": "Рис с курицей",
        "categoryId": "ready_meals",
        "emoji": "🍛",
        "price": 350,
        "image": "images/products/rice_chicken.jpg",
        "unit": "за порцию",
        "description": "Готовый рацион с рисом и курицей. Лёгкий формат для быстрого горячего обеда.",
    },
    {
        "id": "beef_buckwheat",
        "title": "Гречка с говядиной",
        "categoryId": "ready_meals",
        "emoji": "🥩",
        "price": 350,
        "image": "images/products/beef_buckwheat.jpg",
        "unit": "за порцию",
        "description": "Готовый рацион с гречкой и говядиной. Сытный вариант для обеда в дороге или дома.",
    },
    {
        "id": "chicken_soup",
        "title": "Куриный суп",
        "categoryId": "ready_meals",
        "emoji": "🥣",
        "price": 250,
        "image": "images/products/chicken_soup.jpg",
        "unit": "за порцию",
        "description": "Лёгкий куриный суп в формате готового рациона. Подходит для быстрого перекуса.",
    },
    {
        "id": "beef_soup",
        "title": "Говяжий бульон",
        "categoryId": "ready_meals",
        "emoji": "🍲",
        "price": 280,
        "image": "images/products/beef_soup.jpg",
        "unit": "за порцию",
        "description": "Говяжий бульон для горячего приёма пищи. Удобно взять с собой в поездку.",
    },
    {
        "id": "sausage_domashnyaya",
        "title": "Колбаса Домашняя",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 3080,
        "image": "images/products/sausage_domashnyaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная колбаса из линейки мясных деликатесов. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_sibirskaya",
        "title": "Колбаса Сибирская",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 3080,
        "image": "images/products/sausage_sibirskaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная колбаса с насыщенным мясным вкусом. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_kamskaya",
        "title": "Колбаса Камская",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 3080,
        "image": "images/products/sausage_kamskaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная колбаса для нарезки, закусок и домашних блюд. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_pikantnaya",
        "title": "Колбаса Пикантная",
        "categoryId": "sausage",
        "emoji": "🌶",
        "price": 2380,
        "image": "images/products/sausage_pikantnaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная колбаса с пикантным вкусом. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_venskaya",
        "title": "Колбаса Венская",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 3080,
        "image": "images/products/sausage_venskaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная Венская колбаса для нарезки и перекуса. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_orekhovaya",
        "title": "Колбаса Ореховая",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 3080,
        "image": "images/products/sausage_orekhovaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная Ореховая колбаса с мягким мясным вкусом. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_originalnaya",
        "title": "Колбаса Оригинальная",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 3080,
        "image": "images/products/sausage_originalnaya.jpg",
        "unit": "за палку",
        "description": "Полукопчёная Оригинальная колбаса из мясной линейки. Цена указана примерно за 1 палку.",
    },
    {
        "id": "sausage_originalnaya_syrokopchenaya",
        "title": "Сырокопчёная Оригинальная",
        "categoryId": "sausage",
        "emoji": "🥓",
        "price": 5180,
        "image": "images/products/sausage_originalnaya_syrokopchenaya.jpg",
        "unit": "за палку",
        "description": "Сырокопчёная полусухая Оригинальная колбаса. Плотный вкус, цена указана примерно за 1 палку.",
    },
    {
        "id": "horse_konina_rublenaya",
        "title": "Конина рубленая",
        "categoryId": "horsemeat",
        "emoji": "🥩",
        "price": 4520,
        "image": "images/products/horse_konina_rublenaya.jpg",
        "unit": "за палку",
        "description": "Копчёно-варёная рубленая конина. Подходит для нарезки и мясной тарелки.",
    },
    {
        "id": "horse_konina_pressovannaya",
        "title": "Конина прессованная",
        "categoryId": "horsemeat",
        "emoji": "🥩",
        "price": 5180,
        "image": "images/products/horse_konina_pressovannaya.jpg",
        "unit": "за штуку",
        "description": "Копчёно-варёная прессованная конина. Плотный мясной деликатес для нарезки.",
    },
    {
        "id": "horse_steak",
        "title": "Стейк из конины",
        "categoryId": "steak",
        "emoji": "🥩",
        "price": 8400,
        "image": "images/products/horse_steak.jpg",
        "unit": "за штуку",
        "description": "Стейк из конины. Мясная позиция для сытного горячего блюда.",
    },
    {
        "id": "fat_solenyy_bryushnoy",
        "title": "Жир солёный брюшной",
        "categoryId": "fat",
        "emoji": "🧂",
        "price": 1225,
        "image": "images/products/fat_solenyy_bryushnoy.jpg",
        "unit": "за штуку",
        "description": "Солёный брюшной жир. Подходит для нарезки, закусок и добавления к блюдам.",
    },
    {
        "id": "fat_kopchenyy_bryushnoy",
        "title": "Жир копчёный брюшной",
        "categoryId": "fat",
        "emoji": "🥓",
        "price": 2030,
        "image": "images/products/fat_kopchenyy_bryushnoy.jpg",
        "unit": "за штуку",
        "description": "Копчёный брюшной жир с выраженным ароматом. Подходит для закусок и нарезки.",
    },
)

MINI_APP_PRODUCTS = tuple(
    (item["id"], item["title"])
    for item in MINI_APP_PRODUCT_CATALOG
)
MINI_APP_PRODUCT_IDS = frozenset(product_id for product_id, _ in MINI_APP_PRODUCTS)
MINI_APP_PRODUCT_TITLES = {
    product_id: title for product_id, title in MINI_APP_PRODUCTS
}
MINI_APP_PRODUCT_BY_ID = {
    str(item["id"]): item
    for item in MINI_APP_PRODUCT_CATALOG
}
